name: Check & Release

on:
  release:
    types: [ published ]

jobs:
  # NPM install is done in a separate job and cached to speed up the following jobs.
  build_and_test:
    name: Build & Test
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10, 12, 14]

    steps:
      -
        uses: actions/checkout@v2
      -
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: Cache Node Modules
        if: ${{ matrix.node-version == 14 }}
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            build
          key: cache-${{ github.run_id }}-v14
      -
        name: Install Dependencies
        run: npm install
#      -
#        name: Run Tests
#        run: npm test

  deploy:
    name: Publish to NPM
    needs: [build_and_test]
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2
      -
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      -
        name: Load Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            build
          key: cache-${{ github.run_id }}-v14
      -
        name: Publish to NPM
        run: NODE_AUTH_TOKEN=${{secrets.NPM_TOKEN}} npm publish --access public
